server:
  port: 8083
spring:
  application:
    name: sentinel-flow-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    # Sentinel配置
    sentinel:
      transport:
        # 将当前服务链接到 Sentinel 控制台
        dashboard: http://127.0.0.1:8080

