spring:
  application:
    name: openfeign-provider
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        group: DEFAULT_GROUP
        namespace: 0ebbe328-e689-407b-b953-27ac1b860664
        server-addr: 127.0.0.1:8848
