server:
  port: 8081
spring:
  application:
    name: auth-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 4e0aaccb-4302-4bae-872d-2ae61471d885
        username: root
        password: root
        group: DEFAULT_GROUP
feign:
  client:
    config:
      default:
        logger-level: none
        connect-timeout: 2000
        read-timeout: 3000
logging:
  level:
    com.ming.auth.feign.UserFeignClient : debug
