server:
  port: 8082
spring:
  application:
    name: users-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/citydb?serverTimezone=Asia/Shanghai&unicode=true&characterEncoding=utf-8
    username: root
    password: admin123
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        group: DEFAULT_GROUP
        namespace: 4e0aaccb-4302-4bae-872d-2ae61471d885
mybatis:
  type-aliases-package: com.ming.userservice.entity
  mapper-locations: classpath:/mappers/*.xml
